changes in validation message
ShrutiSachpara/event-management pull request #5
Opened 2024-01-19 09:52 UTC by ShrutiSachpara

2024-01-19 13:02 UTC, krishna2919 approved these changes

2024-01-22 07:48 UTC, SwetaaRampariya requested changes

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.html
> +                Please enter a valid email address.
this message should be come from constants file.

in constants file you can add all the strings which you need in future as well.

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.html
> +                Please enter a valid otp.
this message should be come from constants file.

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.html
> +                Please enter a valid password.
this message should be come from constants file.

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.html
> +                Please enter a valid password.
this message should be come from constants file.

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.html
> +                <span class="bx bx-arrow-back me-1"></span>Back to Login
this message should be come from constants file.

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/forgot-password/forgot-password.component.ts
> +      Validators.pattern('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$'),
do not add regex here .

2024-01-22 07:48 UTC, SwetaaRampariya commented on src/app/login/login.component.ts
> +        .subscribe((response: any) => {
do not use any type.

2024-01-23 08:29 UTC, merged